### PR TITLE
ML model training and Evaluation

### PR DESCRIPTION
**Pull request by zackt113**
Hi Team, 

I am done with the model training and evaluation. Please have a look.

As per discussed in our meeting, @stevenleung2018 could you please do me a favour to check if the whole notebook works by loading data from S3? The whole process takes less than 7 minutes! And if it does work then the local reading code could be deleted! Thank you for your checking!

Let me know if you guys would like to add anything. Thank you!

BTW, I also changed the name of the milestone 3 directory because the name contains typos before. 

Zack

### CODE REVIEW

**Comment by stevenleung2018** [comment]
@zackt113 Thanks for the work.  I will check this tomorrow (Tues, April 12).  Goodnight and all the best with quiz tomorrow!

**Comment by stevenleung2018** [comment]
@zackt113 Thanks for the work.  I'm reviewing the files one by one.  
Regarding the 3 images under the folder "images", they are those samples provided by Gittu, right?  So you are only committing the files just as placeholders, right?  I think Task1 and Task2 screen caps should come from me.  I'm not sure which task the file `eg.png` corresponds to.

FYI, I'm still trying to start the lab so that I can test your Task3 notebook.

**Comment by stevenleung2018** [comment]
It looks like I only need to test the Task3 notebook.  I will ignore the other files.  The changes I bring in for Tasks 1 and 2 will go with my own PR.  Please correct me if I'm wrong.

**Comment by zackt113** [comment]
@stevenleung2018, Yes. The only thing I did with the folder is to rename the folder. I think Macy accidentally missed a letter before so, I just deleted that one and commit exactly the same one. I think all things in the folder are just like placeholders. The only thing I made changes to is the task three notebook. So, feel free to delete those screenshots, those were just from Gittu's example! Thank you!

**Comment by zackt113** [comment]
If everything goes well on S3 for task 3, please let me know and you can delete my codes for loading data locally and replace it with the one reading from S3. Everything except for reading data should be good to go.

**Review by stevenleung2018 — APPROVED** [review]
@zackt113 I have tested your Task3 notebook with the S3 bucket.  It works.  Please, as you suggested, change the code to read the file from S3 directly and merge your PR.  Thanks.

**Pull request merged**
